Cleanup code - st55392 Karel Andres
rodi0878/NNPTP21-1 pull request #10
Opened 2021-10-19 13:14 UTC by kar-los97

Přejmenování tříd Cplx -> ComplexNumber, Poly -> Polynome a jejich některých parametrů.
Přesun logiky z třídy Main do vlastní třídy NewtonFractal a rozdělení do více kratších metod.
Přejmenování některých proměnných a metod -> zvolil jsem výstižnější název (dle toho co metoda dělá a k čemu slouží proměnná).

2021-10-26 07:00 UTC, rodi0878 requested changes
Please look at mentioned problems and try to fix them

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/Mathematics/ComplexNumber.cs
> +        public double Imaginari { get; set; }
ImaginarI???

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/Mathematics/ComplexNumber.cs
> +                ComplexNumber x = obj as ComplexNumber;
x?

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/Mathematics/ComplexNumber.cs
> +        public readonly static ComplexNumber Zero = new ComplexNumber()
constant not at the top of class

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/Mathematics/Polynome.cs
> +        public void Add(ComplexNumber coe)
missing doc comment, please use them consistently in all project

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            polynome = new Polynome();
extract polynome creation code to method

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            double xmin = doubleargs[0];
method is named "ColorizeBmpOutput" and not "parse args"

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            for (int i = 0; i < intargs[0]; i++)
dont like "intargs[0]" please refactor to something more meaningful

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +                    ox = new ComplexNumber()
extract creation of ox and settings of its arguments to non-zero values

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            var id = 0;
this should be index not id

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            Color vv = colors[id % colors.Length];
vv?

2021-10-26 07:00 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            vv = Color.FromArgb(vv.R, vv.G, vv.B);
this row doesnt do anything

2021-10-27 08:04 UTC, kar-los97 commented
Problémy opraveny

2021-10-29 19:12 UTC, rodi0878 commented
Možná lokálně u Vás, ale na githubu není žádný nový commit k dispozici...

2021-10-30 08:42 UTC, kar-los97 commented
Omlouvám se za, neprovedl jsem push. Teď už by měli na gitu být všechny změny.

2021-10-30 12:54 UTC, rodi0878 commented
Projekt stále obsahuje celou řadu nedostatku:
- pořadí metod v ComplexNumber je nerozumné, bylo by vhodné metody logicky (tematicky) seřadit
- Polynome::Add(coe) - coe?
- Polynome::Evaluate(x) - zbytečné vytváření dočasné proměnné
- NewtonFractal::CreateComplexNumberAndEditZeroParams - mix double a float konstanty
- NewtonFractal::ColorizeBmpOutput - nepřesný název, co to je "ox", "id" (žádné ID se v programu nikde nepoužívá)
- NewtonFractal::DoNewtonMethod - literály 30, 0.5
- NewtonFractal::FindSOlutionRootNumber - zbytečně neefektivní algoritmus procházející celý cyklus

2021-11-01 07:20 UTC, kar-los97 commented
Úpravy provedeny

2021-11-02 08:18 UTC, rodi0878 commented
Akceptováno

2021-11-02 08:18 UTC, closed without merging