Petr Dolejš - cleancode - NNPTP21-1
rodi0878/NNPTP21-1 pull request #13
Opened 2021-11-16 16:41 UTC by DOL7JS

Renamed branch to dev

2021-11-18 06:16 UTC, rodi0878 requested changes
There are few things that still need cleaning up. Please look at them and update your patch.

2021-11-18 06:16 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            for (int q = 0; q < 30; q++)
why q?

2021-11-18 06:16 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            float iteration = 0;
why float? i see only incrementation and not a single float/double operation

2021-11-18 06:16 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            var id = 0;
index not id

2021-11-18 06:16 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            colorForPixel = Color.FromArgb(colorForPixel.R, colorForPixel.G, colorForPixel.B);
this line does nothing - remove

2021-11-18 06:16 UTC, rodi0878 commented on INPTPZ1/Program.cs
> +            NewtonFractal newtonFractal = new NewtonFractal(args);
i really dont like hiding all the work in the constructor. its not a good style; please create atleast one method which will do real work and call it. constructor is only for setting up of object and not for these calculations

2021-11-18 11:51 UTC, DOL7JS commented
Refactored

- Renamed variable in for cycle - q => i
- Refactored float to int
- Renamed id to index
- Removed useless line
- Created new method

2021-11-22 12:34 UTC, rodi0878 commented
accepted

2021-11-22 12:34 UTC, closed without merging