Refactoring NNPTP21-1 project
rodi0878/NNPTP21-1 pull request #14
Opened 2021-12-09 04:56 UTC by dejv67

Pull request contains improvements and code cleanup.

2021-12-09 06:24 UTC, rodi0878 requested changes
There is quite a lot of unclean things... Please look at attached comments and update your pull request.

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/Mathematics/ComplexNumber.cs
> +        public float ImaginaryPart { get; set; }
change real and imaginary parts to same data type

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/Mathematics/ComplexNumber.cs
> +            ComplexNumber tmp = this.Multiply(new ComplexNumber() { RealPart = b.RealPart, ImaginaryPart = -b.ImaginaryPart });
tmp?

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/Mathematics/ComplexNumber.cs
> +            var tmp2 = b.RealPart * b.RealPart + b.ImaginaryPart * b.ImaginaryPart;
tmp2?

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/Mathematics/Polynomial .cs
> +            int i = 0;
why here and not directly in for? also see "j"

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +        private const string DEFAUL_FILENAME = "../../../out.png";
typo

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +        private static void CreatePicture()
too complex method, make it shorter and simpler

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            float it = 0;
why are iterations in float?

2021-12-09 06:24 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +            var rootId = 0;
according to use this is index and not id

2021-12-09 23:08 UTC, dejv67 commented
Required unclean parts of code from first pull request were fixed.

2021-12-14 10:36 UTC, rodi0878 commented
Accepted

2021-12-14 10:36 UTC, closed without merging