Cleancode
rodi0878/NNPTP21-1 pull request #9
Opened 2021-10-17 17:28 UTC by tomik27

První pokus.

2021-10-26 06:54 UTC, rodi0878 requested changes
Please look at mentioned problems. There is quite a few things to clean up... Also use "format code" on all source code files now its in a complete mess.

It would be nice to do some cleaning in tests part of project.

2021-10-26 06:54 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +            public readonly static ComplexNumber Zero = new ComplexNumber(0, 0);
constants should be at a top of class

2021-10-26 06:54 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +          public   ComplexNumber(double Re, double Im) {
use a proper "format code" tool, there is a mess in blank characters

2021-10-26 06:54 UTC, rodi0878 commented on INPTPZ1/ComplexNumber.cs
> +            public ComplexNumber Add(ComplexNumber addition)
please reorder methods so that all mathematical operations are close together

2021-10-26 06:54 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +          //  image.saveImage();
delete dead code

2021-10-26 06:54 UTC, rodi0878 commented on INPTPZ1/NewtonFractal.cs
> +       public void setPolynomial() {
name of methods doesnt follow C# naming conventions; also set method without parameters is strange, find a better name

2021-10-26 06:54 UTC, rodi0878 commented on INPTPZ1/Point.cs
> +        public double x { get; set; }
also broken naming conventions for properties

2021-11-01 08:56 UTC, tomik27 commented
Problems fixed.

2021-11-02 08:16 UTC, rodi0878 commented
Accepted

2021-11-02 08:16 UTC, closed without merging